### ISSUE TITLE
Support for dekstop devices / mouse click

### ISSUE THREAD

**Issue by angelaki** [mooalot/alphabetical-scroll-bar#1]
Hey, really love your work! Are you planning to support regular desktop targets, too? Or maybe done it, yet? Otherwise, would you like me to contribute to this project?

**Comment by mooalot** [comment]
Hello angelaki! Sure, I would love to add support for desktop. If you need it now, feel free to contribute to the project tho. If you can wait a few days, I'll add the support and let you know.

**Comment by angelaki** [comment]
Since I'm super interested in your approach I'd like to wait and see 😉 But if you're too busy I sure can do it myself 👍 Up to you!

**Comment by mooalot** [comment]
Great I'll try to get it done in the next few days!

**Comment by angelaki** [comment]
Maybe get connected via some instant messenger? To exchange some ideas? Interested?

**Comment by angelaki** [comment]
Done
